services:
  ambeserver:
    container_name: AMBEserver
    image: m8wat/ambeserver-amd64:latest     # for x86_64 systems
    # image: m80wat/ambeserver-aarch64:latest # for arm64 systems (RPi5)
    hostname: ambeserver_container
    networks:
      ambeserver:
        ipv4_address: 10.178.1.2
    ports:
      - "2460:2460/udp"
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    deploy:
      resources:
        limits:
          memory: 32M
        reservations:
          memory: 6M
    restart: always

networks:
  ambeserver:
    name: "ambeserver_network"
    ipam:
      driver: default
      config:
        - subnet: 10.178.1.0/29
