services:
  ambeserver:
    image: m8wat/ambeserver-amd64:0
    container_name: ambeserver
    hostname: t5810-ambeserver
    networks:
      ambeserver:
        ipv4_address: 10.58.1.10
    ports:
      - "2460:2460/udp"
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    deploy:
      resources:
        limits:
          memory: 32M
        reservations:
          memory: 6M
    restart: always

networks:
  ambeserver:
    name: "ambeserver_network"
    ipam:
      driver: default
      config:
        - subnet: 10.178.1.8/29
